// Generated by CoffeeScript 1.11.1
var childProcess, semver, spawn, trim;

childProcess = require("child_process");

semver = require("semver");

module.exports = function(src, options) {
  var args, bare, bin, dest, version, versions;
  if (options == null) {
    options = {};
  }
  dest = options.o;
  bare = options.b;
  version = options.v;
  if (!src) {
    console.log("missing src");
    return;
  }
  if (!dest) {
    console.log("missing dest [-o]");
    return;
  }
  if (!version) {
    console.log("missing version [-v]");
    return;
  }
  versions = require("../versions");
  version = semver.maxSatisfying(versions, version);
  if (!version) {
    console.log("unsupported version: " + options.v);
    return;
  }
  bin = __dirname + "/../versions/" + version + "/bin/coffee";
  args = [bin, "-c"];
  bare && args.push("-b");
  dest && args.push("-o", dest);
  args.push(src);
  return spawn("node", args, {
    cwd: process.cwd(),
    encoding: "utf8"
  });
};

trim = function(str) {
  return str.replace(/[\r\n]+$/, "");
};

spawn = function(command, args, options) {
  var proc;
  proc = childProcess.spawnSync(command, args, options);
  if (proc.error) {
    throw proc.error;
  }
  if (proc.stderr.length > 0) {
    throw Error(trim(proc.stderr));
  }
  return trim(proc.stdout);
};
